FROM postgres:16

# Set working directory
WORKDIR /var/lib/postgresql/data

# Check if the database directory exists (indicates existing data)
RUN [ ! -d "$PGDATA" ] && echo "Database directory not found, initializing..." || echo "Database directory found, skipping initialization."

#ENTRYPOINT ["docker-entrypoint.sh"]
